version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000" # Correct format: list with key-value pairs as strings
    volumes:
      - .:/code
    environment:
      DJANGO_ENV: development
      POSTGRES_DB: StockEcom
      POSTGRES_USER: nickbiiy
      POSTGRES_PASSWORD: nickbiiy@123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: StockEcom
      POSTGRES_USER: nickbiiy
      POSTGRES_PASSWORD: nickbiiy@123
    ports:
      - "5432:5432"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: ["npm", "start"]
